### ISSUE TITLE
How to make browser reflect updated title?

### ISSUE THREAD

**Issue by sabbiu** [justswim/cra-metatag-demo#1]
![image](https://user-images.githubusercontent.com/19733021/38452068-eb92cb5e-3a5b-11e8-8009-8b5cab8c4bba.png)

I know, this repo is actually useful for one looking to favor the search engine. 

- When I route to home page first, I will get all the meta and title description rendered with that specific URL.
- Then, when I route to about page i am still stuck with Home page title as it was the actual rendered html from the server. (as you can see in the photo, I'm in about us page but stuck with home title)

> Is there a way to reflect the changes in the browser title after routing? (Also without refreshing the page and without server side rendering)

BTW, Thanks for the repo.

**Comment by justswim** [comment]
You can use something like React Helmet (https://github.com/nfl/react-helmet) in your client side code to manage the title as you transition from page to page on the client. This repo is just a demo for the server side rendering of dynamic meta tags.

**Comment by sabbiu** [comment]
@justswim Thanks!
